version: '3.3'
services:
    redis:
        ports:
            - '6379:6379'
        container_name: redis_container
        image: redis
    mysql:
        image: mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: craft